import type {
  AiBriefingData,
  BriefingActionItem,
  BriefingSummaryStats,
} from "./types";

export const MOCK_BRIEFING_STATS: BriefingSummaryStats = {
  hotLeadsCount: 5,
  followUpsTodayCount: 8,
  overdueFollowUpsCount: 3,
  newLeadsCount: 4,
  staleLeadsCount: 6,
  activeOpportunityValue: 485000,
  activeOpportunityValueFormatted: "₹4,85,000",
};

export const MOCK_AI_BRIEFING: AiBriefingData = {
  summary:
    "You have 3 high-priority leads today. Rahul should be contacted first because his ₹30,000 opportunity is overdue by 2 days.",
  keyPoints: [
    "Rahul (Score 91) has an overdue follow-up on a ₹30,000 deal; probability drops 35% after 48h.",
    "Sameer reviewed your proposal 18 hours ago — optimal window to follow up and close.",
    "2 fresh inbound leads arrived before noon and have a 4x higher conversion rate if called within 2 hours.",
  ],
  recommendation:
    "Complete Rahul's call and Sameer's proposal follow-up first before moving to new lead outreach.",
  generatedAt: "Today at 08:30 AM",
};

export const MOCK_BRIEFING_ACTIONS: BriefingActionItem[] = [
  {
    id: "action-1",
    title: "Call Rahul",
    subtitle: "Score 91 — overdue follow-up",
    description: "Website redesign project. Last spoke 2 days ago; promised quote walkthrough.",
    leadId: "lead-rahul-01",
    leadName: "Rahul Sharma",
    phone: "+91 98765 43210",
    score: 91,
    opportunityValue: 30000,
    formattedValue: "₹30,000",
    priority: "Critical",
    isDone: false,
    dueTime: "Overdue by 2 days",
    tag: "Overdue Follow-up",
    suggestedActionType: "call",
  },
  {
    id: "action-2",
    title: "Follow up with Sameer",
    subtitle: "Proposal Sent — ₹30,000",
    description: "Custom ERP module proposal submitted. Sameer opened email twice today.",
    leadId: "lead-sameer-02",
    leadName: "Sameer Patel",
    phone: "+91 98234 56789",
    score: 84,
    opportunityValue: 30000,
    formattedValue: "₹30,000",
    priority: "Important",
    isDone: false,
    dueTime: "Today 11:30 AM",
    tag: "Proposal Sent",
    suggestedActionType: "whatsapp",
  },
  {
    id: "action-3",
    title: "Contact 2 new leads before noon",
    subtitle: "Inbound web form inquiries — High intent",
    description: "Pooja Verma & Rohit Gupta submitted requests for CRM setup in the last 4 hours.",
    leadId: "lead-pooja-03",
    leadName: "Pooja Verma",
    phone: "+91 97112 34567",
    score: 78,
    opportunityValue: 25000,
    formattedValue: "₹25,000",
    priority: "Critical",
    isDone: false,
    dueTime: "Before 12:00 PM",
    tag: "New Leads",
    suggestedActionType: "call",
  },
  {
    id: "action-4",
    title: "Re-engage Amit Deshmukh",
    subtitle: "Score 88 — becoming stale (5 days)",
    description: "Expressed strong interest in annual maintenance contract. Needs quick check-in.",
    leadId: "lead-amit-04",
    leadName: "Amit Deshmukh",
    phone: "+91 99887 76655",
    score: 88,
    opportunityValue: 60000,
    formattedValue: "₹60,000",
    priority: "Important",
    isDone: false,
    dueTime: "Today 3:00 PM",
    tag: "Stale Warning",
    suggestedActionType: "followup",
  },
  {
    id: "action-5",
    title: "Send revised specs to Neha",
    subtitle: "Qualified lead — Budget ₹40,000",
    description: "Requested API documentation and hosting requirements before board review.",
    leadId: "lead-neha-05",
    leadName: "Neha Kapoor",
    phone: "+91 91234 98765",
    score: 72,
    opportunityValue: 40000,
    formattedValue: "₹40,000",
    priority: "Normal",
    isDone: false,
    dueTime: "Today 5:00 PM",
    tag: "Qualified",
    suggestedActionType: "whatsapp",
  },
];
