import type { Lead } from "@/features/leads/types";

// Phase 2 presentation data only. Delete this file when real Lead data is connected.
export const mockLeads: Lead[] = [
  {
    id: "demo-lead-001",
    name: "Demo Lead One",
    phone: "+91 00000 00001",
    email: "lead.one@example.test",
    business: "Sample Studio",
    industry: "Professional Services",
    source: "Website",
    budget: 75000,
    status: "New",
    quotedAmount: null,
    lastContactDate: null,
    nextFollowUpDate: "2026-09-15",
    notes: "Temporary example used to demonstrate the lead detail layout.",
    createdAt: "2026-09-12",
  },
  {
    id: "demo-lead-002",
    name: "Demo Lead Two",
    phone: "+91 00000 00002",
    email: "lead.two@example.test",
    business: "Example Foods",
    industry: "Food & Beverage",
    source: "Referral",
    budget: 120000,
    status: "Qualified",
    quotedAmount: 98000,
    lastContactDate: "2026-09-13",
    nextFollowUpDate: "2026-09-17",
    notes: "Temporary qualified-lead example. No customer data is represented.",
    createdAt: "2026-09-08",
  },
  {
    id: "demo-lead-003",
    name: "Demo Lead Three",
    phone: "+91 00000 00003",
    email: "",
    business: "Placeholder Retail",
    industry: "Retail",
    source: "Social",
    budget: 180000,
    status: "Proposal Sent",
    quotedAmount: 150000,
    lastContactDate: "2026-09-14",
    nextFollowUpDate: "2026-09-19",
    notes: "Temporary proposal example for responsive UI testing.",
    createdAt: "2026-09-03",
  },
];
