import type { SmartNotification } from "./types";

/**
 * Isolated mock notifications data.
 * Can be safely replaced or removed once backend notifications integration is wired.
 */
export const initialMockNotifications: SmartNotification[] = [
  {
    id: "notif-1",
    leadId: "lead-101",
    leadName: "Rahul Sharma",
    business: "Apex Logistics",
    phone: "+91 98765 43210",
    type: "overdue_followup",
    typeLabel: "Overdue Follow-up",
    priority: "critical",
    reason: "Rahul has a ₹30,000 opportunity and no activity for 3 days. Follow-up scheduled 2 days ago was missed.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
    recommendedAction: "Call today",
    status: "unread",
    amount: 30000,
    stage: "Proposal Sent",
    dueDate: "2 days overdue",
  },
  {
    id: "notif-2",
    leadId: "lead-102",
    leadName: "Priya Patel",
    business: "TechNova Solutions",
    phone: "+91 98123 45678",
    type: "lead_becoming_stale",
    typeLabel: "Lead Becoming Stale",
    priority: "critical",
    reason: "High-value lead (₹1,20,000) with no client touchpoint for 4 days after initial proposal review.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    recommendedAction: "Send WhatsApp re-engagement",
    status: "unread",
    amount: 120000,
    stage: "Qualified",
    dueDate: "4 days stagnant",
  },
  {
    id: "notif-3",
    leadId: "lead-103",
    leadName: "Amit Verma",
    business: "Zion Retail",
    phone: "+91 99887 76655",
    type: "hot_lead_attention",
    typeLabel: "Hot Lead Needs Attention",
    priority: "critical",
    reason: "Lead score is 92. Viewed pricing breakdown twice today with high purchase intent.",
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 mins ago
    recommendedAction: "Call today before 4:00 PM",
    status: "unread",
    amount: 85000,
    stage: "Proposal Sent",
  },
  {
    id: "notif-4",
    leadId: "lead-104",
    leadName: "Neha Singh",
    business: "Kavya Enterprises",
    phone: "+91 97654 32109",
    type: "followup_due_today",
    typeLabel: "Follow-up Due Today",
    priority: "important",
    reason: "Contract review call scheduled for 2:30 PM today regarding annual retainer.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
    recommendedAction: "Follow up today at 2:30 PM",
    status: "unread",
    amount: 50000,
    stage: "Contacted",
    dueDate: "Today, 2:30 PM",
  },
  {
    id: "notif-5",
    leadId: "lead-105",
    leadName: "Rohit Mehra",
    business: "Skyline Infra",
    phone: "+91 98450 12345",
    type: "proposal_needs_followup",
    typeLabel: "Proposal Needs Follow-up",
    priority: "important",
    reason: "Quotation of ₹65,000 sent 3 days ago. No decision logged yet.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    recommendedAction: "Check proposal status",
    status: "read",
    amount: 65000,
    stage: "Proposal Sent",
  },
  {
    id: "notif-6",
    leadId: "lead-106",
    leadName: "Ananya Roy",
    business: "Bloom Studios",
    phone: "+91 98220 99887",
    type: "new_lead_uncontacted",
    typeLabel: "New Lead Not Contacted",
    priority: "important",
    reason: "Inbound website lead waiting 4 hours without first outreach touchpoint.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    recommendedAction: "Make initial contact",
    status: "unread",
    stage: "New",
  },
  {
    id: "notif-7",
    leadId: "lead-107",
    leadName: "Vikram Malhotra",
    business: "Matrix Dynamics",
    phone: "+91 98900 11223",
    type: "high_value_opportunity",
    typeLabel: "High-Value Opportunity",
    priority: "important",
    reason: "Deal size is ₹2,50,000. Decision maker requested customized implementation timeline.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    recommendedAction: "Share timeline document",
    status: "read",
    amount: 250000,
    stage: "Qualified",
  },
  {
    id: "notif-8",
    leadId: "lead-108",
    leadName: "Pooja Gupta",
    business: "Organic Roots",
    phone: "+91 98111 22334",
    type: "ai_recommended_action",
    typeLabel: "AI Recommended Action",
    priority: "normal",
    reason: "Previous notes indicate interest in Q4 bulk discounts. Good time to re-engage.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    recommendedAction: "Send Q4 discount template",
    status: "read",
    amount: 20000,
    stage: "Contacted",
  },
  {
    id: "notif-9",
    leadId: "lead-109",
    leadName: "Karan Rao",
    business: "Vertex Automations",
    phone: "+91 98333 44556",
    type: "missed_followup",
    typeLabel: "Missed Follow-up",
    priority: "normal",
    reason: "Scheduled follow-up yesterday was not completed.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    recommendedAction: "Reschedule follow-up",
    status: "resolved",
    amount: 40000,
    stage: "Qualified",
  },
];
